server:
  port: 8901

nginx:
  server_name: 192.168.1.102

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.102:3306/cross-gateway?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.102
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/config/mybatis-config.xml
